### ISSUE TITLE
[PE-D][Tester D] Sample add command does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W10-1/tp#121]
![image.png](https://raw.githubusercontent.com/tjch-o/ped/main/files/f4dbf4f6-09a6-4f54-b69d-aba3d5c00038.png)

When I copy and paste the sample command they gave when trying out the add command I get a invalid command format.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tjch-o/ped#2

**Comment by ravern** [comment]
This has been addressed.
