### ISSUE TITLE
[PE-D][Tester A] Hyperlink for UG is not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W10-1/tp#130]
![image.png](https://raw.githubusercontent.com/Song-Mengfei/ped/main/files/bfa567a7-b26b-4909-9238-31fe0d198213.png)

I could click them but they have no response

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Song-Mengfei/ped#5

**Comment by ravern** [comment]
This is solved in #187.
