### ISSUE TITLE
[PE-D][Tester E] Comment tag result display 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-1/tp#135]
**Input Command**
`add s/A0343434D n/erferferferf Doe p/98765432 e/johnd@example.com g/4.9 pg/B+ is/2 t/pastTA 
`
![Screenshot 2023-11-03 at 4.35.36 PM.png](https://raw.githubusercontent.com/yuxunn/ped/main/files/7e380780-5aad-468f-8e23-b956f3d91a70.png)

Users can see that the comment tag is optional. It would be better if the result says 
`New applicant added: erferferferf Doe; Phone: 98765432; Email: johnd@example.com; GPA: 4.9; Comment: none; Tags: [pastTA].` instead :)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yuxunn/ped#4

**Comment by LHeng1** [comment]
It can be added as a `Planned Enhancement` under DG.
