### ISSUE TITLE
[PE-D][Tester D] Clickable contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W10-1/tp#142]
![image.png](https://raw.githubusercontent.com/tjch-o/ped/main/files/b25963ec-b06d-4b66-a3d6-51ec9c74806a.png)

I can mouse click on each contact and it just remains on the current screen. Should it be clickable so that each time I click it goes to the relevant contact? 

![image.png](https://raw.githubusercontent.com/tjch-o/ped/main/files/2878d6c0-6113-4b91-b9af-21c98f04bce1.png)

Even in this image I am selecting the 2nd contact just from start up.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tjch-o/ped#6

**Comment by ravern** [comment]
This app is meant to be a command-line application, so clicking doesn't work. The behaviour works as intended.
